from .canary_suite import load_canary_suite, write_canary_suite
from .detectors import (
    detect_exact_duplicates,
    detect_group_overlap,
    detect_near_duplicates,
    detect_preprocessing_leakage,
    detect_suspicious_feature_leakage,
    detect_temporal_leakage,
    empty_findings_dataframe,
)
from .report import generate_audit_report
from .scoring import FindingScoreInput, score_branch
from .schema import (
    AUDIT_RESULTS_SCHEMA,
    FINDINGS_COLUMN_CONTRACT,
    METRICS_BEFORE_AFTER_SCHEMA,
    PROVENANCE_SCHEMA,
    SPLIT_MANIFEST_SCHEMA,
    build_example_audit_results,
    build_example_metrics_before_after,
    build_example_provenance,
    build_provenance_block,
    build_example_split_manifest,
    validate_audit_results,
    validate_findings_columns,
    validate_metrics_before_after,
    validate_provenance_block,
    validate_split_manifest,
)

__all__ = [
    "FindingScoreInput",
    "AUDIT_RESULTS_SCHEMA",
    "FINDINGS_COLUMN_CONTRACT",
    "METRICS_BEFORE_AFTER_SCHEMA",
    "PROVENANCE_SCHEMA",
    "SPLIT_MANIFEST_SCHEMA",
    "detect_exact_duplicates",
    "detect_group_overlap",
    "detect_near_duplicates",
    "detect_preprocessing_leakage",
    "detect_suspicious_feature_leakage",
    "detect_temporal_leakage",
    "empty_findings_dataframe",
    "generate_audit_report",
    "build_example_audit_results",
    "build_example_metrics_before_after",
    "build_example_provenance",
    "build_provenance_block",
    "build_example_split_manifest",
    "load_canary_suite",
    "score_branch",
    "validate_audit_results",
    "validate_findings_columns",
    "validate_metrics_before_after",
    "validate_provenance_block",
    "validate_split_manifest",
    "write_canary_suite",
]
